### ISSUE TITLE
process-step should find legend in text field

### ISSUE THREAD

**Issue by WardCunningham** [joshuabenuck/denowiki#31]
The human-readable legend for a process step should be kept in the item's text field, not the legend field. That way, should a page with this item travel beyond the servers that offer the plugin, the "help" rendering will be more useful.

See implementation: https://github.com/joshuabenuck/seran-wiki/blob/4aa1129dc60e0f79818af15ca9b95a9967dcfd6c/client/process-step.mjs#L46

No need for these items not sharing what they know.

![image](https://user-images.githubusercontent.com/12127/77557674-45d56d00-6e77-11ea-9b9c-352a02bbf0bf.png)

(This is my bug. I suggested the field name without thinking. I'm the one to fix it and and adjust all known uses. Unfortunately my poor choice is already part of my permanent record.)

**Comment by joshuabenuck** [comment]
Fixed in https://github.com/joshuabenuck/seran-wiki/commit/91713453b1134f04612c4e868963bf02bc398381 and https://github.com/joshuabenuck/seran-scrape/commit/dd6dc162adb53e32b74ec2718acf84c11aaabfc2

Here's an example of dev.wiki.randombits.xyz viewing a local copy of the scrape meta-site.
![image](https://user-images.githubusercontent.com/306384/77600061-f4070400-6ec3-11ea-8da9-3442d4aec49d.png)
